CREATE TABLE IF NOT EXISTS game_stats (
    id              INTEGER PRIMARY KEY,
    min             INTEGER,
    fgm             NUMERIC,
    fga             NUMERIC,
    fg_pct          NUMERIC,
    fg3m            NUMERIC,
    fg3a            NUMERIC,
    fg3_pct         NUMERIC,
    ftm             NUMERIC,
    fta             NUMERIC,
    ft_pct          NUMERIC,
    oreb            NUMERIC,
    dreb            NUMERIC,
    reb             NUMERIC,
    ast             NUMERIC,
    stl             NUMERIC,
    blk             NUMERIC,
    turnover        NUMERIC,
    pf              NUMERIC,
    pts             NUMERIC,
    player_id       INTEGER REFERENCES players(id),
    player_first_name VARCHAR(100),
    player_last_name  VARCHAR(100),
    player_team_id  INTEGER REFERENCES teams(id),
    game_id         INTEGER REFERENCES games(game_id),
    game_date       DATE,
    game_season     INTEGER,
    game_postseason BOOLEAN,
    home_team_score INTEGER,
    visitor_team_score INTEGER,
    home_team_id    INTEGER REFERENCES teams(id),
    visitor_team_id INTEGER REFERENCES teams(id),
    load_date       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
